service: my-serverless-app

provider:
  name: aws
  runtime: nodejs14.x # oder eine andere unterstützte Node.js-Version
  region: eu-central-1 # oder eine andere Region deiner Wahl

functions:
  app:
    handler: index.handler # Verweis auf die index.js-Datei
    events:
      - http:
          path: s3-event
          method: post

plugins:
  - serverless-offline # Optional für lokale Entwicklung